project:
  type: book

book:
  title: "references"
  author: "Norah Jones"
  date: "3/26/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter.qmd
    - third.qmd
    - appendices.qmd
    - bibliography.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    filters:
      - section-bibliographies.lua # needs pandoc version >= 2.11 to work



